# Generated by Django 5.0.7 on 2024-07-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blo_title', models.CharField(max_length=100, verbose_name='Título')),
                ('blo_subtitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Título')),
                ('blo_description', models.TextField(verbose_name='Texto do Blog')),
                ('blo_image', models.ImageField(blank=True, null=True, upload_to='images/blog', verbose_name='Imagem de Capa')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
