# Generated by Django 5.0.7 on 2024-07-24 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='descricion',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Produto'),
        ),
        migrations.AddField(
            model_name='products',
            name='pro_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
