# Generated by Django 5.0.7 on 2024-07-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_descricion_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/produto', verbose_name='Imagem de Capa'),
        ),
    ]
