# Generated by Django 5.0.7 on 2024-07-30 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_products_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTecnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cattec_name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria da Tecnologia')),
            ],
            options={
                'verbose_name': 'Categoria da Tecnologia',
                'verbose_name_plural': 'Categorias das Tecnologias',
            },
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.CreateModel(
            name='Tecnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tec_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('tec_description', models.TextField(verbose_name='Texto do Tecnologia')),
                ('tec_image', models.ImageField(blank=True, null=True, upload_to='images/tecnologia', verbose_name='Imagem de Capa')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('tec_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categorytecnology')),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
            },
        ),
    ]
