# Generated by Django 5.0.7 on 2024-07-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_categorytecnology_alter_products_options_tecnology'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
    ]
